name: Package Application with Pyinstaller

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p dist/windows

      - uses: actions/checkout@v3

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
        with:
          path: .
          spec: main.spec

      - uses: actions/upload-artifact@v2
        with:
          name: sqm-parser
          path: dist/
