name: Package Application with Pyinstaller

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  run-pyinstaller:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller main.spec
      # Optionally verify that it works (provided that it does not need user interaction)
      # - run: ./dist/your-code/your-code
      - uses: svenstaro/upload-release-action@2.7.0
        with:
          file: dist/main.exe
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: "sqm parser"
          body: "This is an automatic release of SQM parser ${{ github.ref_name }}"
          make_latest: true
